# ==========================================================
# dropQbsd \xe2\x80\x94 .xsession
#
# X session startup. Sourced by xenodm at login.
# Copy to: ~/.xsession
#
# user:      indicator_xfce4 + XFCE (conductor desktop)
# all others: indicator_cwm + cwm (domain compartments)
# ==========================================================

[ -f /etc/profile ] && . /etc/profile
xrandr --dpi 96

# --- dropQbsd domain indicator ---
case "$USER" in
    user)
        /opt/dropQbsd/bin/indicator_xfce4 &
        ;;
    *)
        /opt/dropQbsd/bin/indicator_cwm &
        ;;
esac

# --- window manager / desktop environment ---
case "$USER" in
    user)
        exec /usr/local/bin/startxfce4
        ;;
    *)
        exec /usr/local/bin/cwm
        ;;
esac

