# dropQbsd -- example /etc/doas.conf
# Minimal configuration. user has NO doas access.
# The only path to root is the run_app setuid binary,
# which can only launch domain applications.

permit nopass root
